"""add manager department to user

Revision ID: 3e7b887a128b
Revises: 45cde743c239
Create Date: 2026-06-25 11:06:47.074585

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3e7b887a128b"
down_revision: Union[str, Sequence[str], None] = "45cde743c239"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("manager_department_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "users", "departments", ["manager_department_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "manager_department_id")
    # ### end Alembic commands ###
