"""create employee table

Revision ID: 4e27a2fd7569
Revises: b70c16994af2
Create Date: 2026-06-11 15:40:04.111989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e27a2fd7569'
down_revision: str = '9159a3c1e527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('employee', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('employee', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_employee_id'), 'employee', ['id'], unique=False)
    op.create_unique_constraint(None, 'employee', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_index(op.f('ix_employee_id'), table_name='employee')
    op.alter_column('employee', 'age', existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employee', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('employee', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
