"""add first_name last_name

Revision ID: 52aa77d70b11
Revises: 52761639d7b4
Create Date: 2026-06-12 18:30:49.824854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52aa77d70b11'
down_revision: Union[str, Sequence[str], None] = '52761639d7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('employee', sa.Column('last_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'last_name')
    op.drop_column('employee', 'first_name')
    # ### end Alembic commands ###
