"""add department audit fields

Revision ID: 5f7841e5659b
Revises: 52aa77d70b11
Create Date: 2026-06-15 11:15:01.131693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f7841e5659b'
down_revision: Union[str, Sequence[str], None] = '52aa77d70b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('departments', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('departments', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('departments', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('departments', sa.Column('updated_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'updated_by')
    op.drop_column('departments', 'created_by')
    op.drop_column('departments', 'updated_at')
    op.drop_column('departments', 'created_at')
    op.drop_column('departments', 'description')
    # ### end Alembic commands ###
