"""fresh start

Revision ID: 9159a3c1e527
Revises: 
Create Date: 2026-06-10 13:31:31.410710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9159a3c1e527'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('employee', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('employee', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('employee', sa.Column('updated_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'updated_by')
    op.drop_column('employee', 'created_by')
    op.drop_column('employee', 'updated_at')
    op.drop_column('employee', 'created_at')
    # ### end Alembic commands ###
