"""link user and employee

Revision ID: be30f1aee363
Revises: 107d0a6facb3
Create Date: 2026-06-16 12:03:33.344637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be30f1aee363'
down_revision: Union[str, Sequence[str], None] = '107d0a6facb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'employee', ['user_id'])
    op.create_foreign_key(None, 'employee', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_column('employee', 'user_id')
    # ### end Alembic commands ###
